trigger:
  branches:
    include:
      - master  # Replace 'main' with the appropriate branch name

pool:
  vmImage: 'ubuntu-latest'  # Choose the appropriate agent based on your requirements

steps:
- script: |
    # Install Terraform (if not already installed)
    # Replace the version with the desired Terraform version
    curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/

  displayName: 'Install Terraform'
